
package com.yxb.cms.dao;

import com.yxb.cms.domain.vo.AnnouncementInfoUser;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

/**
 * 公告用户信息DAO
 */
@Mapper
public interface AnnouncementInfoUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_announcement_info_user
     *
     * @mbggenerated Fri Sep 01 00:04:17 CST 2017
     */
    int deleteByPrimaryKey(Integer announcementInfoUserId);



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_announcement_info_user
     *
     * @mbggenerated Fri Sep 01 00:04:17 CST 2017
     */
    int insert(AnnouncementInfoUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_announcement_info_user
     *
     * @mbggenerated Fri Sep 01 00:04:17 CST 2017
     */
    int insertSelective(AnnouncementInfoUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_announcement_info_user
     *
     * @mbggenerated Fri Sep 01 00:04:17 CST 2017
     */
    AnnouncementInfoUser selectByPrimaryKey(Integer announcementInfoUserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_announcement_info_user
     *
     * @mbggenerated Fri Sep 01 00:04:17 CST 2017
     */
    int updateByPrimaryKeySelective(AnnouncementInfoUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_announcement_info_user
     *
     * @mbggenerated Fri Sep 01 00:04:17 CST 2017
     */
    int updateByPrimaryKey(AnnouncementInfoUser record);


    /**
     * 根据公告Id,删除公告用户信息
     * @param announcementId 公告Id
     */
    void deleteAnnInfoUserByAnnouncementId(@Param("announcementId") Integer announcementId);


}