
package com.yxb.cms.dao;

import com.yxb.cms.domain.vo.DataCleaning;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

/**
 * 数据清洗DAO
 */
@Mapper
public interface DataCleaningMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_data_cleaning
     *
     * @mbggenerated Mon Sep 18 14:28:55 CST 2017
     */
    int deleteByPrimaryKey(Integer dataId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_data_cleaning
     *
     * @mbggenerated Mon Sep 18 14:28:55 CST 2017
     */
    int insert(DataCleaning record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_data_cleaning
     *
     * @mbggenerated Mon Sep 18 14:28:55 CST 2017
     */
    int insertSelective(DataCleaning record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_data_cleaning
     *
     * @mbggenerated Mon Sep 18 14:28:55 CST 2017
     */
    DataCleaning selectByPrimaryKey(Integer dataId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_data_cleaning
     *
     * @mbggenerated Mon Sep 18 14:28:55 CST 2017
     */
    int updateByPrimaryKeySelective(DataCleaning record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_data_cleaning
     *
     * @mbggenerated Mon Sep 18 14:28:55 CST 2017
     */
    int updateByPrimaryKey(DataCleaning record);

    /**
     * 批量插入数据清洗数据
     * @param list
     */
    void insertDataCleanBatch(List<DataCleaning> list);

    /**
     * 查询用户访问量
     * @return
     */
    List<DataCleaning> selectDataCleanListByLoginInfo();


}