
package com.yxb.cms.dao;

import com.yxb.cms.domain.dto.DataCollectDto;
import com.yxb.cms.domain.vo.SystemLog;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

/**
 * 系统日志DAO
 *
 */
@Mapper
public interface SystemLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_sys_log
     *
     * @mbggenerated Wed Sep 06 23:14:17 CST 2017
     */
    int deleteByPrimaryKey(Integer logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_sys_log
     *
     * @mbggenerated Wed Sep 06 23:14:17 CST 2017
     */
    int insert(SystemLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_sys_log
     *
     * @mbggenerated Wed Sep 06 23:14:17 CST 2017
     */
    int insertSelective(SystemLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_sys_log
     *
     * @mbggenerated Wed Sep 06 23:14:17 CST 2017
     */
    SystemLog selectByPrimaryKey(Integer logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_sys_log
     *
     * @mbggenerated Wed Sep 06 23:14:17 CST 2017
     */
    int updateByPrimaryKeySelective(SystemLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_sys_log
     *
     * @mbggenerated Wed Sep 06 23:14:17 CST 2017
     */
    int updateByPrimaryKey(SystemLog record);



    /**
     * 查询日志总记录数
     * @param systemLog 日志实体
     * @return
     */
    Long selectCountSystemLog(SystemLog systemLog);
    /**
     * 日志信息分页列表显示
     * @param systemLog 日志实体
     * @return
     */
    List<SystemLog> selectSystemLogListByPage(SystemLog systemLog);

    /**
     * 日志信息列表信息List
     * @param systemLog 日志实体
     * @return
     */
    List<SystemLog>selectSystemLogList(SystemLog systemLog);

    /**
     * 根据登陆日志查询用户登录汇总数据<br>
     * 查询当天(不包括)开始前7天的，同一个IP，同一天的用户登陆日志信息汇总.
     *
     * @return
     */
    List<DataCollectDto>selectDataCollectListByLog();


}