
package com.yxb.cms.dao;

import com.yxb.cms.domain.vo.UserRole;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;


/**
 * 用户角色DAO
 */
@Mapper
public interface UserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_user_role
     *
     * @mbggenerated Wed Nov 30 15:15:03 CST 2016
     */
    int deleteByPrimaryKey(Integer userRoleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_user_role
     *
     * @mbggenerated Wed Nov 30 15:15:03 CST 2016
     */
    int insert(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_user_role
     *
     * @mbggenerated Wed Nov 30 15:15:03 CST 2016
     */
    int insertSelective(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_user_role
     *
     * @mbggenerated Wed Nov 30 15:15:03 CST 2016
     */
    UserRole selectByPrimaryKey(Integer userRoleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_user_role
     *
     * @mbggenerated Wed Nov 30 15:15:03 CST 2016
     */
    int updateByPrimaryKeySelective(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_user_role
     *
     * @mbggenerated Wed Nov 30 15:15:03 CST 2016
     */
    int updateByPrimaryKey(UserRole record);

    /**
     * 根据用户Id,查询用户角色信息
     * @param userId 用户Id
     * @return
     */
    List<UserRole> selectUserRolesListByUserId(@Param("userId") Integer userId);


    /**
     * 根据角色Id,查询用户角色信息
     * @param roleId 角色Id
     * @return
     */
    List<UserRole> selectUserRolesListByRoleId(@Param("roleId") Integer roleId);

    /**
     * 根据角色Id删除用户角色信息
     * @param roleId 角色Id
     */
    void deleteUserRoleByRoleId(@Param("roleId") Integer roleId);

    Integer findRoleByUserId(@Param("userId")  Integer userId);

    void approve(Integer userId);
}