
package com.yxb.cms.domain.vo;
/**
 * 站内公告用户信息记录表
 *
 */
public class AnnouncementInfoUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cc_announcement_info_user.announcement_info_user_id
     *
     * @mbggenerated Fri Sep 01 00:04:17 CST 2017
     */
    private Integer announcementInfoUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cc_announcement_info_user.announcement_id
     *
     * @mbggenerated Fri Sep 01 00:04:17 CST 2017
     */
    private Integer announcementId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cc_announcement_info_user.user_id
     *
     * @mbggenerated Fri Sep 01 00:04:17 CST 2017
     */
    private Integer userId;


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cc_announcement_info_user.announcement_info_user_id
     *
     * @return the value of cc_announcement_info_user.announcement_info_user_id
     *
     * @mbggenerated Fri Sep 01 00:04:17 CST 2017
     */
    public Integer getAnnouncementInfoUserId() {
        return announcementInfoUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cc_announcement_info_user.announcement_info_user_id
     *
     * @param announcementInfoUserId the value for cc_announcement_info_user.announcement_info_user_id
     *
     * @mbggenerated Fri Sep 01 00:04:17 CST 2017
     */
    public void setAnnouncementInfoUserId(Integer announcementInfoUserId) {
        this.announcementInfoUserId = announcementInfoUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cc_announcement_info_user.announcement_id
     *
     * @return the value of cc_announcement_info_user.announcement_id
     *
     * @mbggenerated Fri Sep 01 00:04:17 CST 2017
     */
    public Integer getAnnouncementId() {
        return announcementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cc_announcement_info_user.announcement_id
     *
     * @param announcementId the value for cc_announcement_info_user.announcement_id
     *
     * @mbggenerated Fri Sep 01 00:04:17 CST 2017
     */
    public void setAnnouncementId(Integer announcementId) {
        this.announcementId = announcementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cc_announcement_info_user.user_id
     *
     * @return the value of cc_announcement_info_user.user_id
     *
     * @mbggenerated Fri Sep 01 00:04:17 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cc_announcement_info_user.user_id
     *
     * @param userId the value for cc_announcement_info_user.user_id
     *
     * @mbggenerated Fri Sep 01 00:04:17 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}