
package com.yxb.cms.domain.vo;
/**
 * 数据清洗实体
 */
public class DataCleaning {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cc_data_cleaning.data_id
     *
     * @mbggenerated Mon Sep 18 14:28:55 CST 2017
     */
    private Integer dataId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cc_data_cleaning.data_type
     *
     * @mbggenerated Mon Sep 18 14:28:55 CST 2017
     */
    private Integer dataType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cc_data_cleaning.data_time
     *
     * @mbggenerated Mon Sep 18 14:28:55 CST 2017
     */
    private String dataTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cc_data_cleaning.data_count
     *
     * @mbggenerated Mon Sep 18 14:28:55 CST 2017
     */
    private Integer dataCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cc_data_cleaning.data_id
     *
     * @return the value of cc_data_cleaning.data_id
     *
     * @mbggenerated Mon Sep 18 14:28:55 CST 2017
     */
    public Integer getDataId() {
        return dataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cc_data_cleaning.data_id
     *
     * @param dataId the value for cc_data_cleaning.data_id
     *
     * @mbggenerated Mon Sep 18 14:28:55 CST 2017
     */
    public void setDataId(Integer dataId) {
        this.dataId = dataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cc_data_cleaning.data_type
     *
     * @return the value of cc_data_cleaning.data_type
     *
     * @mbggenerated Mon Sep 18 14:28:55 CST 2017
     */
    public Integer getDataType() {
        return dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cc_data_cleaning.data_type
     *
     * @param dataType the value for cc_data_cleaning.data_type
     *
     * @mbggenerated Mon Sep 18 14:28:55 CST 2017
     */
    public void setDataType(Integer dataType) {
        this.dataType = dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cc_data_cleaning.data_time
     *
     * @return the value of cc_data_cleaning.data_time
     *
     * @mbggenerated Mon Sep 18 14:28:55 CST 2017
     */
    public String getDataTime() {
        return dataTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cc_data_cleaning.data_time
     *
     * @param dataTime the value for cc_data_cleaning.data_time
     *
     * @mbggenerated Mon Sep 18 14:28:55 CST 2017
     */
    public void setDataTime(String dataTime) {
        this.dataTime = dataTime == null ? null : dataTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cc_data_cleaning.data_count
     *
     * @return the value of cc_data_cleaning.data_count
     *
     * @mbggenerated Mon Sep 18 14:28:55 CST 2017
     */
    public Integer getDataCount() {
        return dataCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cc_data_cleaning.data_count
     *
     * @param dataCount the value for cc_data_cleaning.data_count
     *
     * @mbggenerated Mon Sep 18 14:28:55 CST 2017
     */
    public void setDataCount(Integer dataCount) {
        this.dataCount = dataCount;
    }
}