
package com.yxb.cms.domain.vo;


import java.io.Serializable;
import java.util.Date;

/**
 * 角色资源关联实体
 */
public class RoleResource implements Serializable{
	
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cc_role_resource.role_res_id
     *
     * @mbggenerated Tue Nov 29 21:23:21 CST 2016
     */
    private Integer roleResId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cc_role_resource.role_id
     *
     * @mbggenerated Tue Nov 29 21:23:21 CST 2016
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cc_role_resource.resource_id
     *
     * @mbggenerated Tue Nov 29 21:23:21 CST 2016
     */
    private Integer resourceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cc_role_resource.creator
     *
     * @mbggenerated Tue Nov 29 21:23:21 CST 2016
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cc_role_resource.create_time
     *
     * @mbggenerated Tue Nov 29 21:23:21 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cc_role_resource.modifier
     *
     * @mbggenerated Tue Nov 29 21:23:21 CST 2016
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cc_role_resource.modifier_time
     *
     * @mbggenerated Tue Nov 29 21:23:21 CST 2016
     */
    private Date modifierTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cc_role_resource.role_res_id
     *
     * @return the value of cc_role_resource.role_res_id
     *
     * @mbggenerated Tue Nov 29 21:23:21 CST 2016
     */
    public Integer getRoleResId() {
        return roleResId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cc_role_resource.role_res_id
     *
     * @param roleResId the value for cc_role_resource.role_res_id
     *
     * @mbggenerated Tue Nov 29 21:23:21 CST 2016
     */
    public void setRoleResId(Integer roleResId) {
        this.roleResId = roleResId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cc_role_resource.role_id
     *
     * @return the value of cc_role_resource.role_id
     *
     * @mbggenerated Tue Nov 29 21:23:21 CST 2016
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cc_role_resource.role_id
     *
     * @param roleId the value for cc_role_resource.role_id
     *
     * @mbggenerated Tue Nov 29 21:23:21 CST 2016
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cc_role_resource.resource_id
     *
     * @return the value of cc_role_resource.resource_id
     *
     * @mbggenerated Tue Nov 29 21:23:21 CST 2016
     */
    public Integer getResourceId() {
        return resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cc_role_resource.resource_id
     *
     * @param resourceId the value for cc_role_resource.resource_id
     *
     * @mbggenerated Tue Nov 29 21:23:21 CST 2016
     */
    public void setResourceId(Integer resourceId) {
        this.resourceId = resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cc_role_resource.creator
     *
     * @return the value of cc_role_resource.creator
     *
     * @mbggenerated Tue Nov 29 21:23:21 CST 2016
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cc_role_resource.creator
     *
     * @param creator the value for cc_role_resource.creator
     *
     * @mbggenerated Tue Nov 29 21:23:21 CST 2016
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cc_role_resource.create_time
     *
     * @return the value of cc_role_resource.create_time
     *
     * @mbggenerated Tue Nov 29 21:23:21 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cc_role_resource.create_time
     *
     * @param createTime the value for cc_role_resource.create_time
     *
     * @mbggenerated Tue Nov 29 21:23:21 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cc_role_resource.modifier
     *
     * @return the value of cc_role_resource.modifier
     *
     * @mbggenerated Tue Nov 29 21:23:21 CST 2016
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cc_role_resource.modifier
     *
     * @param modifier the value for cc_role_resource.modifier
     *
     * @mbggenerated Tue Nov 29 21:23:21 CST 2016
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cc_role_resource.modifier_time
     *
     * @return the value of cc_role_resource.modifier_time
     *
     * @mbggenerated Tue Nov 29 21:23:21 CST 2016
     */
    public Date getModifierTime() {
        return modifierTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cc_role_resource.modifier_time
     *
     * @param modifierTime the value for cc_role_resource.modifier_time
     *
     * @mbggenerated Tue Nov 29 21:23:21 CST 2016
     */
    public void setModifierTime(Date modifierTime) {
        this.modifierTime = modifierTime;
    }
}