
package com.yxb.cms.domain.vo;


import java.io.Serializable;
import java.util.Date;

/**
 * 用户角色关联实体
 *
 */
public class UserRole implements Serializable {
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cc_user_role.user_role_id
     *
     * @mbggenerated Wed Nov 30 15:15:03 CST 2016
     */
    private Integer userRoleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cc_user_role.user_id
     *
     * @mbggenerated Wed Nov 30 15:15:03 CST 2016
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cc_user_role.role_id
     *
     * @mbggenerated Wed Nov 30 15:15:03 CST 2016
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cc_user_role.creator
     *
     * @mbggenerated Wed Nov 30 15:15:03 CST 2016
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cc_user_role.create_time
     *
     * @mbggenerated Wed Nov 30 15:15:03 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cc_user_role.modifier
     *
     * @mbggenerated Wed Nov 30 15:15:03 CST 2016
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cc_user_role.modifier_time
     *
     * @mbggenerated Wed Nov 30 15:15:03 CST 2016
     */
    private Date modifierTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cc_user_role.user_role_id
     *
     * @return the value of cc_user_role.user_role_id
     *
     * @mbggenerated Wed Nov 30 15:15:03 CST 2016
     */
    public Integer getUserRoleId() {
        return userRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cc_user_role.user_role_id
     *
     * @param userRoleId the value for cc_user_role.user_role_id
     *
     * @mbggenerated Wed Nov 30 15:15:03 CST 2016
     */
    public void setUserRoleId(Integer userRoleId) {
        this.userRoleId = userRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cc_user_role.user_id
     *
     * @return the value of cc_user_role.user_id
     *
     * @mbggenerated Wed Nov 30 15:15:03 CST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cc_user_role.user_id
     *
     * @param userId the value for cc_user_role.user_id
     *
     * @mbggenerated Wed Nov 30 15:15:03 CST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cc_user_role.role_id
     *
     * @return the value of cc_user_role.role_id
     *
     * @mbggenerated Wed Nov 30 15:15:03 CST 2016
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cc_user_role.role_id
     *
     * @param roleId the value for cc_user_role.role_id
     *
     * @mbggenerated Wed Nov 30 15:15:03 CST 2016
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cc_user_role.creator
     *
     * @return the value of cc_user_role.creator
     *
     * @mbggenerated Wed Nov 30 15:15:03 CST 2016
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cc_user_role.creator
     *
     * @param creator the value for cc_user_role.creator
     *
     * @mbggenerated Wed Nov 30 15:15:03 CST 2016
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cc_user_role.create_time
     *
     * @return the value of cc_user_role.create_time
     *
     * @mbggenerated Wed Nov 30 15:15:03 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cc_user_role.create_time
     *
     * @param createTime the value for cc_user_role.create_time
     *
     * @mbggenerated Wed Nov 30 15:15:03 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cc_user_role.modifier
     *
     * @return the value of cc_user_role.modifier
     *
     * @mbggenerated Wed Nov 30 15:15:03 CST 2016
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cc_user_role.modifier
     *
     * @param modifier the value for cc_user_role.modifier
     *
     * @mbggenerated Wed Nov 30 15:15:03 CST 2016
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cc_user_role.modifier_time
     *
     * @return the value of cc_user_role.modifier_time
     *
     * @mbggenerated Wed Nov 30 15:15:03 CST 2016
     */
    public Date getModifierTime() {
        return modifierTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cc_user_role.modifier_time
     *
     * @param modifierTime the value for cc_user_role.modifier_time
     *
     * @mbggenerated Wed Nov 30 15:15:03 CST 2016
     */
    public void setModifierTime(Date modifierTime) {
        this.modifierTime = modifierTime;
    }
}